### PR TITLE
Minor update

### PR DESCRIPTION
**Pull request by Delta1977**
Update Manifest.json with Parameter Version for HA 2021.6 compatiblity

See Issue #14

### CODE REVIEW

**Comment by nicolaswehmeyer** [comment]
@opravdin Any chance to get this merged in anytime soon? We've fixed it manually so far in our installations, but this is affecting anyone using the integration right now. Could you provide an update? Many thanks.

**Comment by toot** [comment]
> @opravdin Any chance to get this merged in anytime soon? We've fixed it manually so far in our installations, but this is affecting anyone using the integration right now. Could you provide an update? Many thanks.

How can I fix this manually? Is there an easy way? 😃

**Comment by Delta1977** [comment]
> > @opravdin Any chance to get this merged in anytime soon? We've fixed it manually so far in our installations, but this is affecting anyone using the integration right now. Could you provide an update? Many thanks.
> 
> How can I fix this manually? Is there an easy way? 😃

You could fork the repository and apply there the patch / line as in my PR. then delete the original Integration in HACS and you your cloned repo. 
The keep an eye on the origin and when the PR here is merged you could return to the origin Integration.

Other method is : 
Use temporary my repo: https://github.com/Delta1977/weback-hass which had the patch included

**Comment by SauloSilva** [comment]
Nice @Delta1977 

I appreciate this merge soon @opravdin (=

**Pull request closed without merging**
